lr: 0.01
seed: 1
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 32
val_batch: 32
test_batch: 32
num_workers: 8
model_name: 'encoder-decoder-pmn'
data_filepath: './data/'
dataset: 'air_dancer'
lr_schedule: [100, 200, 300]
num_gpus: 1
epochs: 500
