lr: 0.01
seed: 3
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 64
val_batch: 64
test_batch: 64
num_workers: 8
model_name: 'encoder-decoder-64-pmn'
data_filepath: './data/'
dataset: 'single_pendulum'
lr_schedule: [100, 200, 300]
num_gpus: 1
epochs: 500
