lr: 0.01
seed: 3
if_cuda: True
gamma: 0.1
log_dir: 'logs'
train_batch: 64
val_batch: 64
test_batch: 64
num_workers: 8
model_name: 'encoder-decoder-pmn'
data_filepath: './data/'
dataset: 'fire'
lr_schedule: [50, 100, 300, 700]
num_gpus: 1
epochs: 500
